// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTenMeetings.Models;

#nullable disable

namespace WebTenMeetings.Migrations
{
    [DbContext(typeof(contexto))]
    partial class contextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ParticipantePauta", b =>
                {
                    b.Property<int>("ParticipantesId")
                        .HasColumnType("int");

                    b.Property<int>("PautasVotadasPautaId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantesId", "PautasVotadasPautaId");

                    b.HasIndex("PautasVotadasPautaId");

                    b.ToTable("ParticipantePauta");
                });

            modelBuilder.Entity("WebTenMeetings.Models.Assembleia", b =>
                {
                    b.Property<int>("AssembleiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssembleiaId"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("AssembleiaId");

                    b.ToTable("Assembleia");
                });

            modelBuilder.Entity("WebTenMeetings.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AssembleiaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssembleiaId");

                    b.ToTable("Participante");
                });

            modelBuilder.Entity("WebTenMeetings.Models.Pauta", b =>
                {
                    b.Property<int>("PautaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PautaId"), 1L, 1);

                    b.Property<int?>("AssembleiaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdTotalVotos")
                        .HasColumnType("int");

                    b.HasKey("PautaId");

                    b.HasIndex("AssembleiaId");

                    b.ToTable("Pauta");
                });

            modelBuilder.Entity("ParticipantePauta", b =>
                {
                    b.HasOne("WebTenMeetings.Models.Participante", null)
                        .WithMany()
                        .HasForeignKey("ParticipantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebTenMeetings.Models.Pauta", null)
                        .WithMany()
                        .HasForeignKey("PautasVotadasPautaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebTenMeetings.Models.Participante", b =>
                {
                    b.HasOne("WebTenMeetings.Models.Assembleia", null)
                        .WithMany("Participantes")
                        .HasForeignKey("AssembleiaId");
                });

            modelBuilder.Entity("WebTenMeetings.Models.Pauta", b =>
                {
                    b.HasOne("WebTenMeetings.Models.Assembleia", null)
                        .WithMany("Pautas")
                        .HasForeignKey("AssembleiaId");
                });

            modelBuilder.Entity("WebTenMeetings.Models.Assembleia", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Pautas");
                });
#pragma warning restore 612, 618
        }
    }
}
